// Run once for all items — first = Flash record, last = Pro record
const flash = $input.first().json;
const pro   = $input.last().json;

const diff = JSON.parse(flash.flash_vs_pro_diff);

const jsonReport = JSON.stringify({ flash, pro }, null, 2);

const mdReport = `# Document Analysis Report

**File:** ${flash.filename}
**Processed:** ${flash.processed_at}
**Document ID:** ${flash.document_id}
**Drive File:** ${flash.drive_file_id}${flash.source_zip ? `\n**Source ZIP:** ${JSON.parse(flash.source_zip).name} (${JSON.parse(flash.source_zip).id})` : ''}

## Classification
- **Type:** ${flash.classification}
- **Department:** ${flash.department}
- **Sensitivity:** ${flash.sensitivity}
- **Routing Tag:** ${flash.routing_tag}
- **File Type:** ${flash.file_type}

## Flash Analysis (${flash.model})
- **Sentiment:** ${flash.sentiment}
- **Confidence:** ${flash.confidence_score}
- **Summary:** ${flash.summary}

## Pro Analysis (${pro.model})
- **Sentiment:** ${pro.sentiment}
- **Confidence:** ${pro.confidence_score}
- **Summary:** ${pro.summary}

## Multi-model Comparison
- Classification match: ${diff.classification_match ? '✅ Match' : '⚠️ Differs'}
- Sentiment match: ${diff.sentiment_match ? '✅ Match' : '⚠️ Differs'}
- Flash confidence: ${diff.flash_confidence}
- Pro confidence: ${diff.pro_confidence ?? 'N/A'}

---
*Generated by Prismatic*
`;

return [{
  json: {
    ...flash,
    json_report: jsonReport,
    md_report:   mdReport,
    base_filename: flash.filename.replace(/\.[^/.]+$/, '')
  }
}];
